### ISSUE TITLE
Hook into proxy

### ISSUE THREAD

**Issue by LiShine** [solkimicreb/react-easy-state#10]
I have a wish/suggestion to always do Store.x = 5 instead of Store.setX(5)
But upon this setting I want to do something before or after setting.
I know setters intended for this, but then I have to call it different name than the property....
Maybe it is not good writing, maybe I should do always setX(), everybody doing like this... Please advise

For example if I set todos[i].new = true
Then I trigger some function inside the store.

Could/Should I tap into your Proxy somehow ? Is it called middleware ?

**Comment by solkimicreb** [comment]
Easy State is just a thin React port of the [NX observer util](https://github.com/nx-js/observer-util). If you want to go a bit deeper, I suggest you to check out that library. You can create your own reactions - which trigger on store changes - like this.

```js
import { store } from 'react-easy-state'
import { observe } from '@nx-js/observer-util'

const person = store({
  name: 'Bob'
})

// this runs whenever person.name changes
observe(() => console.log(`Name is set to: ${person.name}`))

// this logs 'Name is set to: Ann'
person.name = 'Ann'
```

Stores are just observables from the observer utils and views are components which have a reactive render method. (Note: this example uses Easy State 4.0.0, with the new names: view instead of easyComp and store instead of easyStore).

I suggest you to create custom reactions with `observe` instead of trying to 'hook into' things. If you think about it, this is a lot more powerful than hooks. Hope this helps, I am closing the issue now.
