### ISSUE TITLE
Highlight platform support

### ISSUE THREAD

**Issue by joshwcomeau** [solkimicreb/react-easy-state#15]
Hi there!

Thanks for your great work on this library, looks really neat!

I have a concern, though. I feel like the "Platform Support" is burying the lede a bit... I imagine many devs will just assume that a React state library won't have any browser-support issues (because *most* JS is polyfill-able, the "common" browser-support concerns are things that touch the DOM, like styling).

I think it's a realistic scenario that someone might create a new app, spend 3 months building it out, and then right before release decide to test it on legacy browsers, only to discover that it's totally broken, and they have to perform a massive refactor to switch to a different state lib to get it to work.

I'm not saying you'd be to blame in this situation: you do make this point clear in the README. But, you know, not everyone reads documentation in its entirely. Especially newer developers who aren't familiar with ES proxies would be susceptible to this.

I think if we pulled the "Platform Support" section to the top, near "Installation", we reduce the risk of this happening dramatically. We could also bold the text about No IE Support 

Also, this is a nit, but I think it's a bit disingenuous to say that *"This may change in the future, if these platforms add ES6 Proxy support."*, since Microsoft will never release another IE, so this will be perpetually broken in IE.

Happy to open a PR if you agree with me!

**Comment by solkimicreb** [comment]
You are right, but I don't want to put any textual info before the installation and usage part. Not getting straight to the point is a big turn off in case of JS libraries.

I am thinking of a browser support matrix instead - at the very top of the repo with explicitly 'redded out' IE and React Native section. Something similar to what VueJS has at the top: https://github.com/vuejs/vue. I think that this would give enough information at a glance without being too disruptive.

We still have to find a browser matrix with a NodeJS (SSR) and React Native column though. I would also add a * to the IE column, which says '* IE will never be supported because of ...'. React Native support will come with time and it is already partially there (iOS is supported, Android isn't).

How do you feel about this?

**Comment by solkimicreb** [comment]
How do you feel about this version: https://github.com/solkimicreb/react-easy-state/blob/docs/browser-support/README.md?

I added a browser support matrix at the very top, which links to the Platform Support section and tweaked the text a bit there.

**Comment by joshwcomeau** [comment]
> How do you feel about this version: https://github.com/solkimicreb/react-easy-state/blob/docs/browser-support/README.md?

Perfect! Thanks so much for updating it, I think you may have made one or two developers' life easier :)

**Comment by solkimicreb** [comment]
It's not yet merged 🙂 I was waiting for your feedback, I am merging it and closing the issue after work.

Thanks for the issue, it will probably save people from unwanted headaches!
