### ISSUE TITLE
make autobind optional

### ISSUE THREAD

**Issue by brumm** [solkimicreb/react-easy-state#20]
I'm really liking the compact state management, however I'm not sure I want my methods to be automagically bound to the class instance. 

Maybe something like `export default view(HelloComp, { autoBind: true })` could be used to explicitly enable this feature?

**Comment by solkimicreb** [comment]
That's understandable. I would keep the current behavior, but make it optional with `view(Comp, { autoBind: false })` and `store(obj, { autoBind: false })` if that works for you. Ultimately I want to remove autoBind - when decorators finally get into the language - in favor of a `@bound` decorator.

**Comment by brumm** [comment]
I can see why you'd want to keep autoBind: true the default, sounds good! :)
Maybe there could be a 'partial application' kinda middleground with something like

```js
const viewWithoutAutoBind = view({ autoBind: false })
export default viewWithoutAutoBind(HelloComp)
```

**Comment by bleeinc** [comment]
Could we instead just have some way to exclude certain functions? like `view(HelloComp, { exclude: ['func1', 'func2'] })`

**Comment by solkimicreb** [comment]
This is though, I would go with an `include` option instead of exclude and I think this should really be handled by a `@bound` decorator.

```js
const person = store({
  @bound setName (name) {
    this.name = name
  }
})
```

My only issue with this change is that CRA does not support decorators yet. Maybe the best course would leave `autoBind` as it is until CRA adds support. @brumm would you be okay with this? I don't want to make breaking changed multiple times.

**Comment by bleeinc** [comment]
It's a tough call for sure. I only recommended exclude because I often find myself needing to bind all but 1 or 2 functions in a component. So I figured it would take less dev effort to exclude those 1-2 functions than to include the 15 others. I wrote my own lib very similar to this before I found yours and my autoBind only bound the methods you told it to like this

`autoBind(['func1', 'func2' ])`

and left everything else alone. But the bigger the project got the more annoying it became to remember to go add the functions I wanted to be bound to the array so I stopped using it as much. 

Btw, just want to say, love the project, I'm starting to refactor some of my stuff to use it now  :)

**Comment by solkimicreb** [comment]
@bleeinc @brumm After some research I decided to remove auto binding from the library in the [next branch](https://github.com/solkimicreb/react-easy-state/tree/next). It seems like it would happen eventually anyways and it is better to do breaking changes - like this - while the library is not widely used yet.

Binding in React has a lot of different solutions (arrow functions, bind in constructor, bound decorator) and everyone has their own favorite. It was a bad decision to include a solution for this in an unrelated, state management library. @bleeinc you could use your own binding solution.

Would this be okay for you?

**Comment by bleeinc** [comment]
@solkimicreb Hmm.. i don't know, I really like the autoBind implementation and I think to keep components simpler it's a must have, and so did my team, one less thing to worry about, I would much prefer the optional route than removing it all together but at the same time you can't make everyone happy. We try to include as few packages as possible so having autoBind built into this was a big plus for my team.

**Comment by brumm** [comment]
@solkimicreb I agree it's somewhat unrelated, and would support removing it.

**Comment by solkimicreb** [comment]
Hi @brumm @bleeinc !

In the end I removed the auto binding. It was unrelated and not really needed as you can use arrow methods for components and simple direct references in case of stores. I added a notice with links to these options and their explanations to the very top of the repo.

Sorry, if this caused any inconvenience.
