### ISSUE TITLE
4.1.2 broken with Create React App v2

### ISSUE THREAD

**Issue by ro-savage** [solkimicreb/react-easy-state#21]
I am getting this error with create-react-app v2 `(react-scripts 2.0.0-next.47d2d941)`, `react 16.2.0` and `react-easy-state 4.1.2` when wrapping a `Class / Stateful` component with `view`.

![image](https://user-images.githubusercontent.com/9244507/36096946-79fe4252-105d-11e8-9951-608945b80421.png)

You can see the issue by cloning this repo: https://github.com/ro-savage/react-easy-state-cra-bug then running `npm start`. It will crash, then look at the `Stateful.js` component, remove `view` and it works fine.

It appears to work fine with CRA v1.

If you think its an issue with `create-react-app` rather than `react-easy-state` please cross post to their repo.

**Comment by ro-savage** [comment]
`react-scripts v2` upgrades to babel 7 and uglifyES. Could it be one of those that is causing the issue?

**Comment by solkimicreb** [comment]
It's actually an issue with UglifyJS and JavaScript itself that I am battling for some time now. I am pretty convinced that there is no elegant solution. Let's take a deeper dive.

CRA 1 uses Webpack 3, which uses UglifyJS 0.x (for minification) and the current UglifyJS can not minify ES6 code.

CRA2 (alpha) uses Webpack 4 (beta), which uses UglifyJS 1 (beta), which has ES6 support.

This causes a few things:

- Even though Easy State only supports ES6 platforms, I have to transpile it to ES5 to support the current CRA, Webpack, UglifyJS toolchain. Without transpilation production builds  - with UglifyJS minification - would break, beacuse they would try to minify ES6 code (Easy State).

- The CRA2 toolchain does not require this, since it uses UglifyJS 1 (with ES6 support).

Now the issue with JavaScript and BabelJS:

- ES6 classes can not be mixed between transpiled and non transpiled code. If you instantiate a transpiled class - which has a superclass - from none-transpiled code (with `new MyClass()`), it will break. This is also true the other way around: using non transpiled classes from a transpiled source breaks too. This is an issue with Babel and the JS spec itself, I can't help here. Basically you either have to use ES6 or ES5 everywhere in your code, if you use classes.

The sad part is that dependencies are not usually transpiled by Babel, so it's the library author's responsibility to transpile or not tranpile their code. I had to make a decision.

My solution is [documented here](https://github.com/solkimicreb/react-easy-state#alternative-builds).

Easy State is transpiled to ES5 by default - even though it results in the same exact platform support spectrum. I still had to do it, to support the currently most popular toolchain (with UglifyJS). I wanted to support forward thinking people too, so Easy State also has an ES6 build for modern toolchains. You can create an alias in your webpack config, which redirects Easy State to the modern ES6 build from the default ES5 build.

**This will be elegantly solved soon:**

The whole reason of the issue is the late ES6 support from UglifyJS. When CRA2, UglifyJS and Webpack 4 all get a stable release I will just drop the ES5 build and legacy toolchain support. I really can't wait to do this!

**Comment by ro-savage** [comment]
Thanks for the excellent response and solutions!

**Comment by solkimicreb** [comment]
Thanks for the issue 🙂

The format and amount of details was really heart warming. I will leave
this open until cra2 gets a stable release.

**Comment by solkimicreb** [comment]
@ro-savage We still have the option of refactoring `view` to do not use OOP inheritance (`extends`). This would remove the part which breaks between ES5 and ES6 (the `super()` call). If you have any ideas how to do this, do it 🙂 Having a smoother support transition between CRA 1 and 2 would be awesome.

**Comment by ro-savage** [comment]
Unfortunately its probably beyond my scope of knowledge without real research (don't now anything about proxies, and only a bit about the js implementation of classes). 

If I get time try something and it works. I'll let you know.

**Comment by solkimicreb** [comment]
I switched the default build to ES6 in version 6, so this should not be an issue anymore 🙂

**Comment by TimChebotarev** [comment]
I've got a similar issue with "react-easy-state": "16.8.6", "react-scripts": "3.0.0" when wrapping a Class component with **view**. I tried to switch to es5 build but it doesn't help.

![image](https://user-images.githubusercontent.com/11838916/58585864-700fcb80-8262-11e9-8dae-7a4328be4640.png)

**Comment by solkimicreb** [comment]
Hi @TimChebotarev! There have been occasional reports of this since cra3 came out. I tried to look into it but couldn't reproduce it. Is there a chance you could share your project with me or is it a strictly closed source one?
