### ISSUE TITLE
Are there any plans for a "strict mode"?

### ISSUE THREAD

**Issue by robertgonzales** [solkimicreb/react-easy-state#25]
Really liking this library, but I have one concern about using it in a larger codebase. Specifically I want to prevent mutations from happening outside `store({})`. I've been using Mobx (which has this functionality) but I'd happily switch over if something like this was included.

Example:
```js
import { store, useStrict } from 'react-easy-state'

useStrict()

const counter = store({
  count: 0,
  increment() {
   this.count += 1
  }
})

counter.count++ // fails w/ warning

counter.increment() // works
```

**Comment by solkimicreb** [comment]
> Specifically I want to prevent mutations from happening outside store({}). I've been using Mobx (which has this functionality) but I'd happily switch over if something like this was included.

MobX strict mode does not prevent this, it prevents you to run code outside of actions. To demonstrate this, I made an inverse from your example.

```js
import { observable, action } from 'mobx'

useStrict()

const counter = observable({
  count: 0,
  increment() {
   counter.count += 1
  }
})

// this works, because it is wrapped in an action
action(() => counter.count++)

// this fails, because `increment` is not an action
counter.increment()
```

MobX needs actions, because it triggers reactions (renders) synchronously after each change, which could result in a lot of unnecessary renders. Actions tell MobX to wait until the code inside is executed and only then run the triggered batched renders.

**Easy State lets React async batch the renders, so it doesn't need actions.**

Why would you like to have strict mode included? Do you need it to enforce code style or do you want to avoid redundant renders? In the latter case, it is not needed. In the former case I would try to create a smart linter rule for you instead.

Run time checks can lay dormant for a long time, if the 'bad code' doesn't execute. Linters catch code styles error before the code is even executed.

**Comment by robertgonzales** [comment]
Ah yeah you're right about mobx. I've been using the class decorators so long I forgot you can declare actions anywhere.

> Do you need it to enforce code style or do you want to avoid redundant renders?

I suppose you could say I want to enforce code style. My goal is just to easily track the source of state mutations. I don't want some random component accidentally mutating state and then have to hunt down where it happened. In my ideal scenario, mutations would have to be declared in the same scope as the store or in some way be connected.

A linter rule sounds like it could work. Can you point me to a solution or starting point?

**Comment by solkimicreb** [comment]
I will think about it 🙂 The debugger (still in development) will also help you with this. It will show you, which mutations triggered the render and where exactly the mutated property is used inside the render.

**Comment by lukeburns** [comment]
This is something that could be handled as a separate library if you're feeling uncertain about including it @solkimicreb. e.g. see https://github.com/lukeburns/immutator. the interface is still finding itself (i'm deciding whether its too much magic), so i'm certainly open to changes or a fork if you'd like to massage it to your liking. This is how you could use it to restrict state mutation in your example:

```js
import { store } from 'react-easy-state'
import immutator from 'immutator'

const counter = immutator(store({
  count: 0
}))

// define a "mutator" — the original, mutable copy of state is passed as a first argument behind the scenes when it is called
counter.increment = state => state.count++

try {
  counter.count++ // throws
} catch (e) {
  console.log('cannot mutate directly. define a mutator.')
}

counter.increment() // works
```

**Comment by solkimicreb** [comment]
That's pretty cool! I think it could be handled as a separate lib, but I also checked how to make linter rules. There are many options for many tastes.
