### ISSUE TITLE
Component state not updated when using functions in store

### ISSUE THREAD

**Issue by jbq** [solkimicreb/react-easy-state#32]
Hi!  Thanks for the great **react easy state** library.

I came across what I believe to be a bug when I decided to store functions in the store.

A reproducible testcase is available at https://github.com/jbq/react-easy-state-function-bug

To start it, type `yarn && yarn start`.

On the web page, click the **Say Hi** button, the message below still says **Hello, World!** instead of the expected **Hi, World!**.

Now in the source code of `src/App.js` change `const hack_enabled = false` to `const hack_enabled = true` and after app is reloaded click on the **Say Hi** button: the message is properly updated.

This is because when `hack_enabled` is turned off, only a function reference changes in the easy state store.  And when it's turned on a string value is also changed to **force** the component update.

**Comment by solkimicreb** [comment]
Indeed, this is true. It is something I did intentionally, but forgot to document though.

Function valued and Symbol keyed properties are opted-out from the reactive wiring in the underlying observer library [here](https://github.com/nx-js/observer-util/blob/master/src/handlers.js#L15). Removing this line would fix the issue without introducing other bugs, but I am not sure about doing it. I added it intentionally to meet with general expectations about reactivity. Generally I want to react on data changes and don't want to react on metadata changes and I consider Symbols and functions metadata. On a side note, the opt out is also a nice boost performance wise.

I see two options and I will do one of them ASAP:

1. Remove the opt-out line to fix this.
2. Document the current behavior.

Either way, you could always use a conditional branch in a single function instead of flipping functions.

I could use some more context to make the decision.

- Did you design your app based on mutating functions or is it something you just stumbled upon while playing around?
- In the former case, do you do this often or was this an exotic case?

Thanks for the issue, it is super clear 🙂

**Comment by jbq** [comment]
Hi and thanks for your answer.  Of course instead of mutating a function I could introduce a scalar state variable and use conditional branching like this:

```
function displayMessage() {
    if (mystore.selectedButton == "hi")
        return <span>Hi</span>

    return <span>Hello</span>
}
```

But I was finding it a bit more elegant to use a function.  Although it's not a big deal to work around this limitation, I think it makes sense to support it, or at least to make it clear that it's not supported.

Cheers!

**Comment by solkimicreb** [comment]
I will test the performance impact of enabling functions today afternoon.

**Comment by jbq** [comment]
Thinking a bit more about this: don't worry too much about the usecase.  Best practises say store is not meant to keep functions or components, but serializable data.  I ended up using the native React Component state to store my function and it works well.

**Comment by solkimicreb** [comment]
Hi! Function properties are observable for some time now, sorry I forgot to mention this in this issue 🤦‍♂️
