### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by dkirchhof** [solkimicreb/react-easy-state#4]
Hey,

i would like to use this react with TypeScript and EasyState. I followed the tutorial on https://www.typescriptlang.org/docs/handbook/react-&-webpack.html, but unfortunately i don't get it to work. I've imported the easyState.js in my index.html and defined it as external in the webpack.config.js...
Actually i don't have any experiences with webpack. So maybe anyone can help me?!

Thanks in regard.

**Comment by solkimicreb** [comment]
Can anyone help here? I have never used TypeScript. (If no one volunteers I will look into it 🙂 )

**Comment by 5achinJani** [comment]
@dkirchhof  `react-easy-state` has nothing to do to support `TypeScript`. You need to have your `WebPack` setup up and working with `TypeScript` loaders to support it for your project. As you don't have experience with `WebPack`  I'd recommend you use [create-react-app](https://github.com/facebookincubator/create-react-app) so that you don't have to deal with `WebPack` setup and stuff. `create-react-app` has out of the box support of [Flow](https://flow.org/) if you want a type system. [Adding flow to create-react-app](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow)

**Comment by solkimicreb** [comment]
@5achinJani Thanks for the help! I am closing this now.

**Comment by mboeddeker** [comment]
@5achinJani that's bullshit!

**Comment by duffman** [comment]
Eeeh? Closing it, why?

**Comment by solkimicreb** [comment]
I added typescript type definitions a while ago. This repo should work with typescript even with no implicit any type. Do you have any issues with it?
