### ISSUE TITLE
Static properties.

### ISSUE THREAD

**Issue by vivekimsit** [solkimicreb/react-easy-state#44]
I was going through the source and found that the HOC will hide static properties on wrapped components. This is a known issue with HOC as mentioned [here](https://reactjs.org/docs/higher-order-components.html).

So, either we should add this thing in the documentation or figure out some robust solution.

**Comment by solkimicreb** [comment]
Hi!

I don't think it hides static props (some HOCs does, but inverted inheritance HOC does not). Can you provide a  code example?

**Comment by solkimicreb** [comment]
> I can see that only few properties are taken from the inherited component.

Check the roles in the inheritance: `class ReactiveHOC extends BaseComp`. Your original component - passed to `view` - is the parent (inherited) and `ReactiveHOC` (inheriting) is the child. There is no need to copy anything from your component to `ReactiveHOC`, since it inherits the from your component `BaseComp` already.

I only copy static props from stateless (function) components, since they can not be inherited from. Copying only React specific props here could be a problem as you mentioned, but people rarely store custom props on functions. It happens much more frequently with classes and static props, which is already handled by the inheritance.

I hope this make sense, I will try to figure out something more robust for stateless components too. (Maybe copying all enumerable own props could work.)

**Comment by vivekimsit** [comment]
> but people rarely store custom props on functions. It happens much more frequently with classes and static props, which is already handled by the inheritance.

I have not much experience with react but that was my only concern, since you more experience with React this makes sense. I am closing this issue for now.

Thanks,
