### ISSUE TITLE
question about component should update

### ISSUE THREAD

**Issue by mendrik** [solkimicreb/react-easy-state#45]
there is just a shallow property check. does that mean render will not be triggered if I would change a property in an array item?

**Comment by solkimicreb** [comment]
Hi!

In a nutshell: it does render. If you wrap every component with `view`, you won't have trouble with this.

If a prop changes shallowly it re-renders the component (normal React behavior). If a prop is an object passed down from a parent component's store, it is already a store itself. (Stores are created recursively from object valued store props, when the prop object is used inside a `view`.) Since the prop is already a store, it behaves like a store. Using it inside a render (`view`) is tracked and mutating any part of it that is used inside the render will cause a re-render.

This is what happens with `store` and `view`. Easy State however does not modify standard React behavior of normal props and state. If you do not wrap components with view or pass down vanilla objects (not store props of any depth) as props and mutate them in the parent, it won't trigger a re-render inside the child.

I hope this helps.

**Comment by mendrik** [comment]
got it, thank you for the explanation!
