### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by mendrik** [solkimicreb/react-easy-state#46]
Hi,

So I’ve been using your library with preact and am quite amazed how well it works. 
I’ve been checking the performance from http://www.stefankrause.net/js-frameworks-benchmark7/table.html also and noticed that the partial updates are standing out a bit.

Do you have any explanation why that is? It’s not a show stopper, just curious :)

Thanks!

**Comment by solkimicreb** [comment]
Hi!

That's a pretty outdated table: [this is the current one](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html) (easy state v5). You can find the most recent results in [this section](https://github.com/krausest/js-framework-benchmark#snapshot-of-the-results) of the benchmark repo.

The reason why partial updates were so slow is the custom batcher Easy State used to have.  It used to batch updates an execute them with `forceUpdate`, which forces an immediate sync update. This had a few issues though.

- It wasn't compatible with React's future async rendering plans.
- It performed badly when a lot of different components had to update in one batch (a 1000 rows for example).

I decided to remove the custom batcher and use `setState` instead of `forceUpdate`. This delegates the scheduling to React. It has the side effect of causing multiple renders sometimes, but it plays nicer with the future plans of React. You can learn more in [this docs section](https://github.com/solkimicreb/react-easy-state#my-component-renders-multiple-times-unnecessarily).

When the async React scheduler is going to ship in all its glory (hopefully React 17) this solution will really shine. Until then it still performs pretty nicely as the newest table shows.

I hope this helped.

**Comment by mendrik** [comment]
Thank you for the explanation!

**Comment by lishine** [comment]
@mendrik Could you share please, How do you use it with preact ?

**Comment by mendrik** [comment]
@lishine I just copied the view decorator source over to my own project, I didn't install it as a dependency. If you check the code it's fairly straight forward to port.

**Comment by lishine** [comment]
Thanks
Indeed the code is not long
But it would help me a lot if you share your port...
BTW is preact still strong and maintained? (It still seems like the smallest alternative to react?)

**Comment by mendrik** [comment]
sure even though I have also some of own magic in my @view decorator and I don't use functional components:
```
import {observe, unobserve} from '@nx-js/observer-util'
import {runMountQueue, runUnmountQueue} from '../util/construct'

export function View<P = {}, S = {}>(Comp: {new (props: P, context?: any): any}): any {

    class ViewComponent<P, S> extends Comp {

        constructor(props, context) {
            super(props, context)
            this.render = observe(this.render, {
                scheduler: () => this.setState({}),
                lazy: true
            })
        }

        componentDidMount() {
            runMountQueue(this as any, this.base)
            if (super.componentDidMount) {
                super.componentDidMount()
            }
        }

        shouldComponentUpdate(nextProps, nextState, nextContext) {
            const {props, state} = this

            // respect the case when user prohibits updates
            if (super.shouldComponentUpdate &&
                !super.shouldComponentUpdate(nextProps, nextState, nextContext)) {
                return false
            }

            // return true if it is a reactive render or state changes
            if (state !== nextState) {
                return true
            }

            // the component should update if any of its props shallowly changed value
            const keys = Object.keys(props)
            const nextKeys = Object.keys(nextProps)
            return nextKeys.length !== keys.length || nextKeys.some(key => props[key] !== nextProps[key])
        }

        componentWillUnmount() {
            if (super.componentWillUnmount) {
                super.componentWillUnmount()
            }
            unobserve(this.render)
            runUnmountQueue(this as any)
        }
    }

    ViewComponent['displayName'] = Comp['displayName']

    return ViewComponent
}
```

**Comment by lishine** [comment]
Ye Man!!! It works!

**Comment by lishine** [comment]
Updated it for functional components:
```
import { Component } from 'preact'
import { observe, unobserve } from '@nx-js/observer-util'
export { observable } from '@nx-js/observer-util'

export function view(Comp) {
    const isStatelessComp = !(Comp.prototype && Comp.prototype.render)
    const BaseComp = isStatelessComp ? Component : Comp

    class ReactiveHOC extends BaseComp {
        constructor(props, context) {
            super(props, context)
            this.render = observe(this.render, {
                scheduler: () => this.setState({}),
                lazy: true
            })
        }
        render() {
            return isStatelessComp
                ? Comp(this.props, this.context)
                : super.render()
        }

        shouldComponentUpdate(nextProps, nextState, nextContext) {
            const { props, state } = this

            // respect the case when user prohibits updates
            if (
                super.shouldComponentUpdate &&
                !super.shouldComponentUpdate(nextProps, nextState, nextContext)
            ) {
                return false
            }

            // return true if it is a reactive render or state changes
            if (state !== nextState) {
                return true
            }

            // the component should update if any of its props shallowly changed value
            const keys = Object.keys(props)
            const nextKeys = Object.keys(nextProps)
            return (
                nextKeys.length !== keys.length ||
                nextKeys.some((key) => props[key] !== nextProps[key])
            )
        }

        componentWillUnmount() {
            if (super.componentWillUnmount) {
                super.componentWillUnmount()
            }
            unobserve(this.render)
        }
    }

    ReactiveHOC['displayName'] = Comp['displayName']

    return ReactiveHOC
}
```

**Comment by dcflow** [comment]
Hey @lishine can you upload a package to npm for the preact version it would be really helpful for anyone using preact.
