### ISSUE TITLE
No `jsnext:main` section?

### ISSUE THREAD

**Issue by mandx** [solkimicreb/react-easy-state#5]
A `jsnext:main` field that points to the ES6 version of the library's code. I see that `package.json` has the `module` field, but it points to the ES5 (transpiled?) code.

**Comment by solkimicreb** [comment]
This is a pretty deep topic. The `jsnext:main` is a deprecated equivalent of the new `module` field.

The `module` field should point to the esm (ES6 modules) build. It should still be transpiled - apart from the `import` / `export` statements - as tools like Babel **do not transpile** code in `node_modules` when your app is bundled (so it is the **authors responsibility to transpile it**). `import` / `export` statements are special in this regard since they are handled by the bundler instead of the transpiler.

Because of this, the `module` field exposes the transpiled build with `import` / `export` statements and the `main` fields exposes the transpiled commonJS build.

As Easy State does not support pre-ES6 browsers so transpiling may not seem to make sense. It is still necessary to support ES5 toolchains though - like UglifyJS. The default minification in Webpack and Create React App does not work with non transpiled code. Because of this I choose to expose the transpiled files by default until the tooling catches up (UglifyJS 3 is still in beta). (The transpiling is done by [buble](https://buble.surge.sh/guide/) to minimize the performance impact. )

If you use an ES6 aware minifier you can use the non transpiled build too. See [this section](https://github.com/solkimicreb/react-easy-state#alternative-builds) about using custom builds.

There is no perfect way of doing this, but I believe this was the best way. I hope this explains it.

**Comment by mandx** [comment]
It does! Thanks so much. I'm aware of the `module` field, but I was not aware of the deprecation status of the `jsnext:main`.
