### ISSUE TITLE
view HoC is blocking react-router V4

### ISSUE THREAD

**Issue by atrauzzi** [solkimicreb/react-easy-state#50]
I've been putting together an application and noticed this morning that when I have a component wrapped with `view`, it loses the ability to work with react router v4.

After some digging, it appears as though [this bit of documentation explains what's happening](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md).

I've been able to patch around this by wrapping my components using their `withRouter` HoC or wrapping the component in an empty `<Route />`, but apparently this is redundant and not optimal according to their documentation.  Is there any way this project can propagate whatever react router (and likely others) needs to continue functioning?

**Comment by solkimicreb** [comment]
Hi!

This affects every library, which uses `shouldComponentUpdate` for performance optimizing (which means pretty much every state management library, including Redux and Mobx). The link you copied has everything you need to workaround this though. You should wrap blocked components with `withRouter()`.

The issue should be fixed in react-router, they use the old context API and inherit the major flaw of it (why it was replaced). I think they will migrate to the new API and remove this mess in a later version, but until then you should use the `withRouter` workaround. It does not pose any practical problems or performance bottlenecks and it is the most widely used solution for having a state management library and React Router in the same project.

(P.S: I am soon releasing `react-easy-stack` with its own Router, which won't have this issue).

**Comment by atrauzzi** [comment]
Awesome! Thanks for all the insights.

Will your router support nested and relative routes?  Anywhere I can read up more on it, especially in contrast to RRv4?

**Comment by solkimicreb** [comment]
Yep, it will. You will have to wait a little bit more for the read up as I am still working on the docs. Sorry for being so secretive, but I don't want to leak it out unfinished.

**Comment by atrauzzi** [comment]
Totally understand. Hopefully it'll be an easy transition from RRv4 if I like it! 😁
