### ISSUE TITLE
TypeError: Class constructor cannot be invoked without 'new'

### ISSUE THREAD

**Issue by vladshcherbin** [solkimicreb/react-easy-state#52]
When compiling a project with babel and target set to latest browsers (last 2 Chrome versions), using `react-easy-state` gives an error:

![screen shot 2018-08-04 at 08 41 59](https://user-images.githubusercontent.com/6711845/43672958-5c05362e-97c2-11e8-8d2e-0609dada9bb7.png)

I made a small example repo (open `index.html` in dist folder):

https://github.com/vladshcherbin/experiments/tree/master/react-easy-state-bug

react-easy-state v5.1.0

There is [some explanation from Dan](https://github.com/facebook/create-react-app/issues/1751#issuecomment-284763003) if it helps.

**Comment by solkimicreb** [comment]
Hi!

Read [this issue (comment)](https://github.com/solkimicreb/react-easy-state/issues/21#issuecomment-364920295) and [this docs section](https://github.com/solkimicreb/react-easy-state#alternative-builds) for the context and fix please.

Let me know if it's not clear what to do after these 🙂

**Comment by vladshcherbin** [comment]
@solkimicreb hm, yep, I saw multiple builds.

However, from the linked issue it's said that `super` in `view` component breaks it, but as far as I can tell `react-redux` also has [super call](https://github.com/reduxjs/react-redux/blob/v5.0.7/src/components/connectAdvanced.js#L117) so there should be probably a way to solve this somehow 🤔

**Comment by solkimicreb** [comment]
Hmm, I will check how they solve it (maybe there is a better transpiling I didn't know of). Thanks for the info.

**Comment by vladshcherbin** [comment]
@solkimicreb yep, I'm sure it's some babel settings. Let's try to figure it out :)

**Comment by solkimicreb** [comment]
Soo, there is a big difference between react-redux and easy-state code. react-redux `Connect` HOC is extending `Component` from react, while easy-state is extending a custom class the developer passes in. `Component` is already distributed in an ES5 compiled form from react, while the class you pass to easy-state `view` may not be compiled, depending on your bundler settings.

I found a way to make it work with `Reflect.construct`, but I will have to spike if it is working on all supported platforms (since it is a pretty new thing). I could also rewrite the code to extend `Component` instead of the custom class, but it would make the whole code more clumsy and could cause different errors. Currently I use something called [inehritance inversion](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e), which automatically makes sure that props and methods are nicely proxied from your class to the HOC. Otherwise I would have to proxy these by hand, which is error prone. 

I am still leaning towards waiting for the CRA2 update with correct es6 minification. It is pretty sad that mainstream tools still do not support ES6 code yet.

**Comment by vladshcherbin** [comment]
@solkimicreb yep, the whole bundling in js with unsupported formats, transpilation, broken minification, etc feels like a joke.

I think we can close this one since I don't know how it is possible to fix this for current set of tools. I also don't believe tools will become better in near future so we will need to fix this manually in bundler configs 🤦‍♂️
