### ISSUE TITLE
Observe all store changes?

### ISSUE THREAD

**Issue by Bebersohl** [solkimicreb/react-easy-state#78]
Is there a way to observe all changes to a store?

This works for when the `name` property changes:
```javascript
import { store, view } from "react-easy-state";
import { observe } from "@nx-js/observer-util";

const person = store({ name: "Bob", age: 3 });

// this logs person.name whenever it changes
observe(() => console.log(person.name));
```
But I'm wondering if it's possible to do something like this:
```javascript
observe(() => console.log(person));
```
Where the observe function fires anytime any property in the person store changes?

**Comment by solkimicreb** [comment]
Hi! What would you like to do exactly? Just log the store on changes?

**Comment by Bebersohl** [comment]
I was hoping to keep an array of previous stores so that I can implement an undo feature in my app.

Something like:
```javascript
const history = []

// on store change
observe(() => history.push(_.cloneDeep(store)));
```

**Comment by solkimicreb** [comment]
That will work perfectly exactly as you wrote it. `cloneDeep` accesses and clones every single property of the store so the reaction will trigger on any property change.

`console.log` is a special case since it accesses properties in a `sub-JS level` in most platforms which cannot be intercepted by Proxies. If you would like to log the store on any change `console.log(JSON.stringify(store))` is the best way since `JSON.stringify` accesses properties in a JS level.

I hope this helped.

**Comment by Bebersohl** [comment]
Oh! It didn't occur to me that cloneDeep would behave differently than console.log.

Thanks!
