### ISSUE TITLE
() => {

### ISSUE THREAD

**Issue by LiShine** [solkimicreb/react-easy-state#8]
Hi,

I am starting to use it and I am amazed how much it saves comparing to using react state!
Love Proxy and what you are doing!

Small stuff:
Apparently declaring functions in the store with () => { does not work. The this no right.
Is it fixable ? I love these short expressions...

Thanks

**Comment by solkimicreb** [comment]
Hi,

I am glad you like the library 🙂 

Arrow functions are special case that I didn't think of. I guess you have an issue with the `this` inside arrow function methods. It is sadly an 'issue' with JavaScript, not really the library. Take this example:

```js
const obj = {
  x: 12,
  logFn () { console.log(this.x) },
  logArrow: () => console.log(this.x)
}

// this logs '12'
obj.logFn()
// this logs 'undefined'
obj.logArrow()
```

Arrow functions use lexical scoping, which means they get the `this` of the function they were defined inside. In this case `logArrow` has the global scope as its `this`, because it was defined in the global scope.  On top of this their `this` context can not be modified with `call`, `apply` or `bind`. They are meant to be used as small utility callbacks inside other functions - like functions passed to `array.map` - not as methods.

Typically React developers use arrow function for component methods. This works because components are classes not objects, and classes are functions. The lexical `this` points to the class in this case. This won't work with objects.

I will try to figure out something (I have no clue how to fix this for now), but I generally advise you to use the method shorthand syntax for methods 🙂  Like this:

```js
const userStore = {
  user: {},
  async fetchUser () {
    this.user = await fetch('/user')
  }
}
```

Let me know if this was not your issue at all 😄

**Comment by solkimicreb** [comment]
Perhaps I could allow classes to be stores, arrow function methods and lexical `this` would work for classes.

**Comment by LiShine** [comment]
You exactly and clearly answered my question!
I have no experience to tell how to make it work.
But, when I use recompose, this of the methods inside lifecycle do access it's properties. Maybe because one the outside it is class. So maybe  wrapping in a class somehow will make the arrow functions work...

**Comment by solkimicreb** [comment]
I thought about this and I don't think that this can or should be 'fixed'. Using the `this` inside an arrow function is meant to work this way, but you are right about wanting to use arrow functions, where it results in shorter code. You could use the object itself instead of `this` in these cases.

```
const store = easyStore({
  x: 10,
  setX: x => store.x = x,
  badSetX: x => this.x = x
})

// this sets store.x to 1
store.setX(1)
// this 'incorrectly' sets window.x to 2 instead of store.x
store.badSetX(2)
```

Hope this helped 🙂 I am closing this now, feel free to reopen if needed.
