### ISSUE TITLE
Setting global store

### ISSUE THREAD

**Issue by LiShine** [solkimicreb/react-easy-state#9]
I have global store like this:
```
const Store = easyStore({
  loading: false
});
```

Then I want to show loading component,  I set Store.loading = true.
Indeed loading shows up.
Then after some procedure or after just delay I set Store.loading = false
And ... no reaction, no rerender.

I do the same inside setTimeout(() => ..., 1000)
And ... it rerenders correctly

I have no clue ... :)

**Comment by LiShine** [comment]
Noticed that react-native not supported. Maybe this is the issue.

**Comment by LiShine** [comment]
Yes, actually :) without developer tools debugger it does not work.
So pity...

**Comment by solkimicreb** [comment]
Thanks for all the feedback, it's really valuable 👍 

I am waiting for Proxy support on React native. I think it still does not support it ): I will double check it tomorrow. (Debug mode supports it, because it uses a different JS engine).

**Comment by solkimicreb** [comment]
I checked and React Native should be supported by now. This is the current status: it should be supported on every Android phone and on iPhones with iOS 10+. I am looking into it 

Could you copy the buggy code here?

Thx 🙂

**Comment by solkimicreb** [comment]
Okay, I checked around again and I have bad news. React native support is still not doable. Proxies are not polyfillable, so I need engine level support. RN uses the JavaScript Core runtime to execute JS. It is native runtime on iOS and it supports Proxies on iOS 10 plus. Android has a different JS runtime, but the RN devs decided to ship a copy of JavaScript core instead of it for consistency I guess. The copy is more than three years old, so it does not support any non polyfillable features since before es6. In a nutshell I  could only support modern iOS and not Android, which is worthless. We have to wait until the RN devs update the JavaScript core on Android for this.

**Comment by LiShine** [comment]
Yes, thanks man! Pity ...

**Comment by LiShine** [comment]
Here there is alternative Proxy implementation for es5. Will it help? 
https://github.com/mweststrate/immer?files=1

**Comment by solkimicreb** [comment]
Not really :( Proxy is not polyfillable, but some parts can be polyfilled. That library exchanges a lot of cool non polyfillable features for es5 support. I am pretty sure that the only option here is to wait for Proxy support. Proxies are slowly getting mainstream with VueJS and MobX starting to consider them. I think the platform support will get better shortly.

I will close this issue and revisit the topic when the RN devs ship a new JavaScript Core for Android, if that's okay for you. I am still thinking about your other issues 🙂
